spring.application.name=cafeteria-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:dev}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dev}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false